DATABASE_FILE = '.\\ressources\database\stats-database.sqlite'
LOG_FILE = '.\logs\stats.log'
LOG_FORMAT = '%(asctime)s - %(message)s'
ROUNDS_FILE = '.\\ressources\data\Rounds.csv'
DRIVERS_FILE = '.\\ressources\data\Drivers.csv'
CONSTRUCTORS_FILE = '.\\ressources\data\Constructors.csv'
DRIVERS_COLUMNS = ['name','trigramme','car_number','nationality']
CONSTRUCTORS_COLUMNS = ['full_name','short_name','paddock_number']
ROUNDS_COLUMNS = ['round_number','round_name','country','circuit','round_date','round_type']
RESULTS_FOLDER = '.\\ressources\\results'
RESULTS_COLUMNS = ['car_position','car_number','constructor_full_name','result_time']
