DATABASE_FILE = '.\\data\\database\\stats-database.sqlite'
LOG_FILE = '.\\logs\\stats.log'
LOG_FORMAT = '%(asctime)s - %(message)s'
ROUNDS_FILE = '.\\data\\Rounds.csv'
DRIVERS_FILE = '.\\data\\Drivers.csv'
CONSTRUCTORS_FILE = '.\\data\\Constructors.csv'
DRIVERS_COLUMNS = ['name','trigramme','car_number','nationality']
CONSTRUCTORS_COLUMNS = ['full_name','result_name','short_name','paddock_number']
ROUNDS_COLUMNS = ['round_number','round_name','country','circuit','round_date','round_type']
RESULTS_FOLDER = ".\\data\\results\\"
RESULTS_COLUMNS = ['Pos','No','Driver','Car','Time']
VALID_SESSION_TYPES = ['Race','Q1','Q2','Q3','Sprint','SQ1','SQ2','SQ3']
